theme: jekyll-theme-minimal
title: SingularityRobotics
description: Coming soon! See launch paper at <a href="{{ '/Foundations%20of%20AI.pdf' | relative_url }}" target="_blank">https://paper.singularityrobotics.net</a>
