theme: jekyll-theme-minimal
title: SingularityRobotics
description: Coming soon! See launch paper at <a href="{{ '/Foundations of AI.pdf' | relative_url }}" target="_blank">https://paper.singularityrobotics.net</a>
